general:
  rootDevPath:
    Gideon: 'E:/Code Repos'
    PinkBabyMonster: 'C:/CodeRepos'
  obsidianVault:
    Gideon:
      name: 'Desktop Vault'
      path: 'E:/Obsidian/Desktop Vault'

powershell:
  byFeature:
    enable_exercism:
      - Gideon
    enable_zoxide:
      - Gideon
    enable_psmux:
      - Gideon
