general:
  rootDevPath:
    Gideon: 'E:/Code Repos'
    PinkBabyMonster: 'C:/CodeRepos'

powershell:
  byFeature:
    enable_exercism:
      - Gideon
    enable_zoxide:
      - Gideon
    enable_psmux:
      - Gideon
