# Set prefix
set -g prefix C-Space

# ===========================================
# Plugins
# ===========================================
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-sensible'
set -g @plugin 'psmux-plugins/psmux-resurrect'
set -g @plugin 'psmux-plugins/psmux-continuum'
set -g @plugin 'psmux-plugins/psmux-pain-control'
#
set -g @plugin 'psmux-plugins/psmux-theme-tokyonight'
#
set -g @resurrect-capture-pane-contents 'on'

set -g @continuum-save-interval '2'
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

# Initialize PPM (keep at the very bottom)
run '~/.psmux/plugins/ppm/ppm.ps1'
